# JARVIS OMEGA - QR Menu Generator (Phase 16)
from __future__ import annotations
import io, base64, json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List
from backend.tools import tool, RiskTier
from backend import business_db

@tool(name="qrmenu.create", description="Create a digital restaurant menu from dish list. Generates Arabic RTL HTML page + QR code.", parameters={"type":"object","properties":{"restaurant_name":{"type":"string"},"phone":{"type":"string","default":""},"dishes":{"type":"array","items":{"type":"object"},"description":"[{name, price_jod, description, category}]"},"output_dir":{"type":"string","default":"./storage/qr_menus"}},"required":["restaurant_name","dishes"]}, risk_tier=RiskTier.TIER_1_REVERSIBLE, category="qr_menu")
async def qrmenu_create(restaurant_name: str, dishes: List[Dict], phone: str = "", output_dir: str = "./storage/qr_menus") -> Dict[str, Any]:
    # Group by category
    cats = {}
    for d in dishes:
        cat = d.get("category", "عام")
        cats.setdefault(cat, []).append(d)
    sections = ""
    for cat, items in cats.items():
        rows = "".join(f'<div class="flex justify-between border-b py-2"><div><span class="font-bold">{i["name"]}</span><p class="text-sm text-gray-500">{i.get("description","")}</p></div><span class="text-indigo-600 font-bold">{i.get("price_jod",0)} د.أ</span></div>' for i in items)
        sections += f'<h2 class="text-xl font-bold mt-6 mb-2 text-indigo-700">{cat}</h2>{rows}'
    html = f"""<!DOCTYPE html><html dir="rtl" lang="ar"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>قائمة {restaurant_name}</title><script src="https://cdn.tailwindcss.com"></script>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Tajawal:wght@400;700&display=swap">
<style>body{{font-family:Tajawal,sans-serif}}</style></head><body class="bg-gray-50 max-w-lg mx-auto p-4">
<h1 class="text-3xl font-bold text-center mb-4">{restaurant_name}</h1>
{f'<p class="text-center text-gray-500 mb-4">للطلب: {phone}</p>' if phone else ''}
{sections}
<p class="text-center text-gray-400 mt-8"> Generated by JARVIS</p></body></html>"""
    out = Path(output_dir); out.mkdir(parents=True, exist_ok=True)
    safe = "".join(c for c in restaurant_name if c.isalnum() or c in "_-") or "menu"
    html_path = out / f"{safe}_menu.html"; html_path.write_text(html, encoding="utf-8")
    # Generate QR pointing to the menu
    qr_b64 = ""
    try:
        import qrcode
        qr = qrcode.QRCode(box_size=10, border=2)
        qr.add_data(str(html_path))
        qr.make()
        buf = io.BytesIO(); qr.make_image().save(buf, "PNG"); qr_b64 = base64.b64encode(buf.getvalue()).decode()
    except ImportError: pass
    # Persist
    rid = business_db.execute("INSERT INTO restaurant_menus (restaurant_name, phone, menu_json, qr_path, status, created_at) VALUES (?, ?, ?, ?, 'menu_created', ?)",
        (restaurant_name, phone, json.dumps(dishes), str(html_path), datetime.utcnow().isoformat()))
    return {"ok": True, "menu_path": str(html_path), "qr_base64": qr_b64, "restaurant_id": rid, "dish_count": len(dishes),
            "pitch": f"بيع لصاحب المطعم: 'اعملك قائمة رقمية بـ QR code بـ 50-200 د.أ + 20 د.أ/شهر استضافة.'"}

@tool(name="qrmenu.list_restaurants", description="List all restaurants with generated menus.", parameters={"type":"object"}, risk_tier=RiskTier.TIER_0_OBSERVE, category="qr_menu")
async def qrmenu_list() -> Dict[str, Any]:
    rows = business_db.rows_to_dicts(business_db.query("SELECT id, restaurant_name, phone, status, monthly_fee_jod, created_at FROM restaurant_menus ORDER BY id DESC"))
    return {"ok": True, "restaurants": rows}

@tool(name="qrmenu.add_dish_descriptions", description="Use LLM to generate appetizing Arabic descriptions for dishes from names.", parameters={"type":"object","properties":{"dish_names":{"type":"array","items":{"type":"string"}}},"required":["dish_names"]}, risk_tier=RiskTier.TIER_1_REVERSIBLE, category="qr_menu")
async def add_dish_descriptions(dish_names: List[str]) -> Dict[str, Any]:
    from backend.services.llm_service import llm_service
    try:
        reply = await llm_service.get_response(
            user_message=f"Dishes: {dish_names}",
            system_instructions='Write appetizing Arabic descriptions for each dish (1 sentence each). Output STRICT JSON: {"dishes":[{"name":string,"description":string}]}',
            inject_memory=False)
        text = reply.strip().lstrip("`").rstrip("`")
        if text.startswith("json"): text = text[4:]
        return {"ok": True, "dishes": json.loads(text).get("dishes",[])}
    except Exception as e: return {"ok": False, "error": str(e)}

PLUGIN_NAME = "qr_menu"; PLUGIN_VERSION = "1.0.0"
PLUGIN_DESCRIPTION = "Restaurant QR menu generator: dishes -> Arabic RTL menu + QR code. Sell for 50-200 JOD."
