# ====================================================================
# JARVIS OMEGA — Droid Models
# ====================================================================
"""
Schemas for cross-device ("droid") command execution over WebSockets.

These models are used to:
- validate execution envelopes
- correlate requests with async results via message IDs
- transport notifications to the backend core
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, Optional

from pydantic import BaseModel, Field, ConfigDict


class DroidCommand(BaseModel):
    """
    Execution request routed to a connected device.

    Attributes:
      id: correlation id generated by backend
      cmd: structural command name e.g. android_whatsapp_send, desktop_os_execute
      x/y/text/key/pkg/ms: optional payload fields used by interpreters
      meta: free-form metadata for logging/tracing
    """

    id: str = Field(..., min_length=1, description="Correlation/message id")
    cmd: str = Field(..., min_length=1, description="Structural command name")
    x: Optional[float] = None
    y: Optional[float] = None
    text: Optional[str] = None
    key: Optional[str] = None
    pkg: Optional[str] = None
    ms: Optional[int] = None
    target_device_id: Optional[str] = None
    meta: Dict[str, Any] = Field(default_factory=dict)

    model_config = ConfigDict(extra="forbid")


class DroidResult(BaseModel):
    """
    Execution result returned by the remote device.
    """

    id: str = Field(..., min_length=1)
    ok: bool
    data: Optional[Dict[str, Any]] = None
    error: Optional[str] = None

    model_config = ConfigDict(extra="forbid")


class DroidNotification(BaseModel):
    """
    Device-originated notification payload (notifications, clipboard updates, etc).
    """

    id: Optional[str] = None
    pkg: Optional[str] = None
    title: Optional[str] = None
    text: Optional[str] = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)

    model_config = ConfigDict(extra="allow")


class DroidEnvelope(BaseModel):
    """
    Envelope transported over WebSocket to remote devices.
    """

    type: str = Field(..., description="Message type: COMMAND|RESULT|NOTIFICATION|HEARTBEAT")
    device_id: str = Field(..., description="Destination/source device id")
    user_id: Optional[str] = None
    correlation_id: Optional[str] = None
    payload: Dict[str, Any] = Field(default_factory=dict)

    model_config = ConfigDict(extra="forbid")
