# ====================================================================
# JARVIS OMEGA - Payments Plugin (Phase 11)
# ====================================================================
"""
Invoices + revenue tracking + Stripe payment links.

  payments.create_invoice  - generate an invoice row + HTML
  payments.send_invoice    - email an invoice to a client
  payments.list_invoices
  payments.mark_paid
  payments.create_stripe_link  - free Stripe Payment Links (per-tx fee, no monthly)
  payments.revenue_summary - aggregate from paid invoices
"""

from __future__ import annotations

import uuid
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional

import httpx

from backend.tools import tool, RiskTier
from backend import business_db
from backend.config import settings
from shared.logger import get_logger

log = get_logger("payments")

_INVOICE_DIR = Path("./storage/sales/invoices")
_INVOICE_DIR.mkdir(parents=True, exist_ok=True)


def _cred(key: str) -> Optional[str]:
    try:
        from backend.services.credentials_vault import credentials_vault
        return credentials_vault.get(key) or None
    except Exception:
        return None


def _next_invoice_number() -> str:
    year = datetime.utcnow().year
    row = business_db.query_one(
        "SELECT number FROM invoices WHERE number LIKE ? ORDER BY id DESC LIMIT 1",
        (f"INV-{year}-%",),
    )
    if not row:
        return f"INV-{year}-0001"
    try:
        last_n = int(row["number"].rsplit("-", 1)[-1])
        return f"INV-{year}-{last_n + 1:04d}"
    except Exception:
        return f"INV-{year}-{uuid.uuid4().hex[:6].upper()}"


# --------------------------------------------------------------------
# Invoices
# --------------------------------------------------------------------

@tool(
    name="payments.create_invoice",
    description="Create an invoice row + an HTML invoice file.",
    parameters={
        "type": "object",
        "properties": {
            "client_id": {"type": "integer"},
            "amount": {"type": "number"},
            "currency": {"type": "string", "default": "USD"},
            "due_date": {"type": "string", "description": "ISO date. Empty = +15 days from now."},
            "notes": {"type": "string", "default": ""},
            "line_items": {
                "type": "array",
                "default": [],
                "items": {"type": "object"},
                "description": "Optional line-item breakdown rendered into the HTML.",
            },
        },
        "required": ["client_id", "amount"],
    },
    risk_tier=RiskTier.TIER_1_REVERSIBLE,
    category="payments",
)
async def payments_create_invoice(
    client_id: int, amount: float, currency: str = "USD",
    due_date: str = "", notes: str = "",
    line_items: Optional[List[Dict[str, Any]]] = None,
) -> Dict[str, Any]:
    line_items = line_items or []
    client = business_db.query_one("SELECT * FROM clients WHERE id = ?", (client_id,))
    number = _next_invoice_number()
    due = due_date or (datetime.utcnow() + timedelta(days=15)).date().isoformat()
    iid = business_db.execute(
        """INSERT INTO invoices (client_id, number, amount, currency, due_date, status, notes, created_at)
           VALUES (?, ?, ?, ?, ?, 'draft', ?, ?)""",
        (client_id, number, amount, currency, due, notes, datetime.utcnow().isoformat()),
    )

    # Render HTML
    items_html = ""
    if line_items:
        rows = "".join(
            f"<tr><td>{li.get('description','')}</td><td>{li.get('qty',1)}</td>"
            f"<td>{li.get('price',0)} {currency}</td>"
            f"<td>{li.get('qty',1) * li.get('price',0)} {currency}</td></tr>"
            for li in line_items
        )
        items_html = (
            '<table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;width:100%">'
            "<tr><th>Description</th><th>Qty</th><th>Unit Price</th><th>Total</th></tr>"
            f"{rows}</table>"
        )

    client_name = client["name"] if client else f"Client #{client_id}"
    html = f"""<!DOCTYPE html><html><head><meta charset="utf-8"><title>{number}</title>
<style>body {{ font-family: Arial; padding: 40px; max-width: 800px; margin: auto; }}</style></head>
<body>
<h1>Invoice {number}</h1>
<p><strong>Bill To:</strong> {client_name}</p>
<p><strong>Issued:</strong> {datetime.utcnow().date().isoformat()}</p>
<p><strong>Due:</strong> {due}</p>
<hr>
{items_html}
<h2 style="text-align:right">Total: {amount} {currency}</h2>
<p>{notes or ''}</p>
<hr>
<p style="color:#666;font-size:12px">Generated by JARVIS OMEGA.</p>
</body></html>"""
    pdf_path = _INVOICE_DIR / f"{number}.html"
    pdf_path.write_text(html, encoding="utf-8")
    business_db.execute("UPDATE invoices SET pdf_path = ? WHERE id = ?", (str(pdf_path), iid))
    return {"ok": True, "invoice_id": iid, "number": number, "path": str(pdf_path)}


@tool(
    name="payments.send_invoice",
    description="Email an invoice PDF/HTML to a client. Requires SMTP creds in vault.",
    parameters={
        "type": "object",
        "properties": {
            "invoice_id": {"type": "integer"},
            "to_override": {"type": "string", "default": "", "description": "Override the client's stored email."},
        },
        "required": ["invoice_id"],
    },
    risk_tier=RiskTier.TIER_4_EXTERNAL,
    category="payments",
)
async def payments_send_invoice(invoice_id: int, to_override: str = "") -> Dict[str, Any]:
    inv = business_db.query_one("SELECT * FROM invoices WHERE id = ?", (invoice_id,))
    if not inv:
        return {"ok": False, "error": f"invoice not found: {invoice_id}"}
    client = business_db.query_one("SELECT email, name FROM clients WHERE id = ?", (inv["client_id"],))
    to = to_override or (client["email"] if client else "")
    if not to:
        return {"ok": False, "error": "no recipient email"}

    body = (
        f"Hello {client['name'] if client else 'Sir/Madam'},\n\n"
        f"Please find invoice {inv['number']} attached/below.\n"
        f"Amount due: {inv['amount']} {inv['currency']}\n"
        f"Due date: {inv['due_date']}\n\n"
        f"Thank you for your business.\n\n- JARVIS OMEGA"
    )
    from plugins.communication.plugin import email_send
    result = await email_send(
        to=to,
        subject=f"Invoice {inv['number']}",
        body=body,
    )
    if result.get("ok"):
        business_db.execute(
            "UPDATE invoices SET status = 'sent' WHERE id = ?", (invoice_id,)
        )
    return result


@tool(
    name="payments.list_invoices",
    description="List invoices. Filter by status.",
    parameters={
        "type": "object",
        "properties": {
            "status": {"type": "string", "default": ""},
            "limit": {"type": "integer", "default": 50},
        },
    },
    risk_tier=RiskTier.TIER_0_OBSERVE,
    category="payments",
)
async def payments_list_invoices(status: str = "", limit: int = 50) -> Dict[str, Any]:
    sql = "SELECT * FROM invoices"
    params: tuple = ()
    if status:
        sql += " WHERE status = ?"
        params = (status,)
    sql += " ORDER BY id DESC LIMIT ?"
    params = params + (limit,)
    rows = business_db.rows_to_dicts(business_db.query(sql, params))
    return {"ok": True, "count": len(rows), "invoices": rows}


@tool(
    name="payments.mark_paid",
    description="Mark an invoice as paid.",
    parameters={
        "type": "object",
        "properties": {
            "invoice_id": {"type": "integer"},
            "stripe_link": {"type": "string", "default": "", "description": "Optional Stripe Payment Link URL used."},
        },
        "required": ["invoice_id"],
    },
    risk_tier=RiskTier.TIER_1_REVERSIBLE,
    category="payments",
)
async def payments_mark_paid(invoice_id: int, stripe_link: str = "") -> Dict[str, Any]:
    if stripe_link:
        business_db.execute(
            "UPDATE invoices SET status = 'paid', stripe_link = ?, paid_at = ? WHERE id = ?",
            (stripe_link, datetime.utcnow().isoformat(), invoice_id),
        )
    else:
        business_db.execute(
            "UPDATE invoices SET status = 'paid', paid_at = ? WHERE id = ?",
            (datetime.utcnow().isoformat(), invoice_id),
        )
    business_db.audit("mark_paid", "payments", target=str(invoice_id))
    return {"ok": True, "invoice_id": invoice_id}


@tool(
    name="payments.create_stripe_link",
    description="Create a Stripe Payment Link. Requires stripe_secret_key in the vault. Free tier — per-transaction fee only.",
    parameters={
        "type": "object",
        "properties": {
            "product_name": {"type": "string"},
            "amount": {"type": "number", "description": "Amount in major currency units (e.g. dollars, not cents)."},
            "currency": {"type": "string", "default": "USD"},
            "quantity": {"type": "integer", "default": 1},
        },
        "required": ["product_name", "amount"],
    },
    risk_tier=RiskTier.TIER_4_EXTERNAL,
    category="payments",
)
async def payments_create_stripe_link(
    product_name: str, amount: float, currency: str = "USD", quantity: int = 1,
) -> Dict[str, Any]:
    key = _cred("stripe_secret_key")
    if not key:
        return {"ok": False, "error": "stripe_secret_key not in vault"}
    try:
        async with httpx.AsyncClient(timeout=30) as client:
            # Create a product + price + payment link in one flow.
            prod = await client.post(
                "https://api.stripe.com/v1/products",
                data={"name": product_name},
                auth=(key, ""),
            )
            if prod.status_code >= 400:
                return {"ok": False, "status": prod.status_code, "error": prod.text[:300]}
            product_id = prod.json().get("id")

            # Stripe wants amount in smallest unit (cents).
            unit_amount = int(round(amount * 100))
            price = await client.post(
                "https://api.stripe.com/v1/prices",
                data={
                    "product": product_id,
                    "unit_amount": unit_amount,
                    "currency": currency.lower(),
                    "type": "one_time",
                },
                auth=(key, ""),
            )
            if price.status_code >= 400:
                return {"ok": False, "status": price.status_code, "error": price.text[:300]}
            price_id = price.json().get("id")

            link = await client.post(
                "https://api.stripe.com/v1/payment_links",
                data={
                    "line_items[0][price]": price_id,
                    "line_items[0][quantity]": str(quantity),
                },
                auth=(key, ""),
            )
            if link.status_code >= 400:
                return {"ok": False, "status": link.status_code, "error": link.text[:300]}
            link_data = link.json()
            return {
                "ok": True,
                "url": link_data.get("url"),
                "id": link_data.get("id"),
                "product_id": product_id,
                "price_id": price_id,
            }
    except Exception as e:
        return {"ok": False, "error": str(e)}


@tool(
    name="payments.revenue_summary",
    description="Aggregate revenue from paid invoices. Returns total, count, average, by-currency breakdown.",
    parameters={
        "type": "object",
        "properties": {
            "days": {"type": "integer", "default": 30, "description": "Lookback window (0 = all time)."},
        },
    },
    risk_tier=RiskTier.TIER_0_OBSERVE,
    category="payments",
)
async def payments_revenue_summary(days: int = 30) -> Dict[str, Any]:
    where = ""
    params: tuple = ()
    if days > 0:
        cutoff = (datetime.utcnow() - timedelta(days=days)).isoformat()
        where = "WHERE status = 'paid' AND paid_at >= ?"
        params = (cutoff,)
    else:
        where = "WHERE status = 'paid'"
    rows = business_db.query(
        f"SELECT currency, COUNT(*) as n, COALESCE(SUM(amount), 0) as total, AVG(amount) as avg FROM invoices {where} GROUP BY currency",
        params,
    )
    out = [
        {"currency": r["currency"], "count": r["n"], "total": r["total"], "avg": r["avg"]}
        for r in rows
    ]
    return {"ok": True, "days": days, "by_currency": out}


PLUGIN_NAME = "payments"
PLUGIN_VERSION = "1.0.0"
PLUGIN_DESCRIPTION = "Invoices + revenue tracking + Stripe Payment Links (per-tx fee, no monthly)."
